apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: amul-recon
  annotations:
    chef/subdomain: related-monster
    chef/namespace: blinkit-apps-saxena-rahul
    chef/s3-prefix: s3://blinkit-ai-chef-builds/blinkit-apps-saxena-rahul/amul-recon/

build:
  artifacts:
  - image: 501578625374.dkr.ecr.ap-south-1.amazonaws.com/chef/blinkit-apps-saxena-rahul/amul-recon/web
    context: ./web
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
